name: Sonar

inputs:
  GITHUB_TOKEN:
    required: true
    type: string
  SONAR_TOKEN:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: coverage.out
        path: ./files

    - uses: actions/download-artifact@v3
      with:
        name: report.json
        path: ./files

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.go.tests.reportPath=files/report.json
          -Dsonar.go.coverage.reportPaths=files/coverage.out
          -Dsonar.sources=.
